var n;browser=chrome;navigator.userAgent.includes("Edg/");
const aa=Boolean,v=Object.values,B=RegExp.prototype.test,ba=RegExp.prototype.exec,ca=Array.isArray,da=Array.from,ea=Array.prototype.includes,C=Math.floor,D=Math.random,E=Object.isExtensible,fa=Function.apply.bind(Array.prototype.push),ha=Function.apply.bind(String.fromCharCode,null),ia=Function.call.bind(String.prototype.charCodeAt),ja=String.fromCharCode,la=Function.bind.bind(function(a){return this[a]}),ma=Function.bind.bind(function(a){return a&&a[this]});
Array.prototype.at||(Array.prototype.at=function(a){0>a&&(a+=this.length);return this[a]});AbortSignal.timeout||(AbortSignal.timeout=function(a){let b=new AbortController;globalThis.setTimeout(b.abort.bind(b),a);return b.signal});const na=B.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),oa=["date","content-type","content-length"];function pa(a,b){return fetch(a,b).catch(()=>null)}function qa(a){return ha(a instanceof ArrayBuffer?new Uint8Array(a):a)}
function ra(a){return E(a)?a.source.replaceAll("\\/","/"):a}function sa(a){return a.replace(/[a-z]/gi,function(b){return ja((b=ia(b))+(13<(b&31)?-13:13))})}function F(){if(this.constructor!==F)return ta.promise;this.promise=new Promise((a,b)=>(this.resolve=a,this.reject=b));ta=this}var ta;F.prototype.g=function(...a){let b=browser.runtime.lastError;b?this.reject(b):this.resolve(...a)};function G(){return F.prototype.g.bind(new F)}const I={};I[-1]=[2,[111,112],[111]];
I[1]=[2,[115,116,117,124,118,119,120,121,127,131,132,123,125,133,126,129,130,134,135],[115,111,112,113,114]];I[2]=[2,[114,113,113,115,116,117,118,122,119,125,126,124,121,120,123,112],[111,112,114]];I[3]=[null,[113,114,115,116,117],[112]];I[4]=[2,[111,101,113,112,114,118,119,124,115,116,117,120,121,122,123],[111]];I[5]=[null,[111,112,113],[111]];I[6]=[null,[],[111]];
const ua={16:1,17:2,18:4,45:8,46:16},va={http:1,https:9,ftp:2,ftps:10,idmreg:12,idmdwnlmfv3:33,idmdwnlmfv4:33,idmdwnlmfv5:33},xa=B.bind(/^(?:https?|socks[45])$/),ya={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},za={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON",
"application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/vnd.yt-ump":"UMP",
"application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI",
"application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8",
"video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S",
"audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
var Aa,Ba,Ca;const J=globalThis,Da=browser.runtime.id,Ea=browser.runtime.getManifest();var Fa=Ea.permissions.includes("notifications")||null;const Ga={16:"images/logo16.png",32:"images/logo32.png"},Ha={16:"images/logo16x.png",32:"images/logo32x.png"},Ia=["127.0.0.1:1001","0.1.0.1:1001"],Ja=RegExp("(?!)"),Ka=["main_frame","sub_frame"],La=["object","image"];var Ma=La.concat("xmlhttprequest","media"),Na=Ka.concat(La,"xmlhttprequest","media","other");
const K=["*://*/*"],Oa=["ftp://*/*"],Pa=K.concat(Oa,"file:///*","about:blank"),Qa=K.concat("about:blank"),Ra=btoa(D().toString().substr(2,9)),Sa=browser.runtime.getURL("captured.html?"+(Ra?`auth=${Ra}&`:"")),Ta=browser.runtime.getURL("welcome.html?"+(Ra?`auth=${Ra}&`:"")),Ua=browser.runtime.getURL("").slice(0,-1),Va=sa("KZYUggcErdhrfg|bcra|fraq|frgErdhrfgUrnqre|hcybnq|ybnqraq|erfcbafrGrkg|srgpu|urnqref|obql|grkg|wfba|trgErnqre|cvcrGuebhtu|Urnqref|npprcg|*/*|nccyvpngvba/iaq.g1p|Erfcbafr|hey|trg"),
Wa=B.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Xa=B.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),Ya=B.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Za=B.bind(/^(MPD|M3U8|F4M)$/i),$a=B.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),ab=B.bind(/^[GPTSDVACRHX]*$/),bb=ba.bind(/^(.*?)(,\s*)?\bapplication\/vnd\.t1c\.(\w+)-([^\s,]+)(?:,\s*)?(.*)$/),cb=ba.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),db=ba.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),
eb=ea.bind([301,302,303,307,308]),fb=/[:,;]/,gb=/[,;]/,hb=[],ib=B.bind(RegExp("messaging host not found","i"));
function jb(a,b,c,e,d,f,g,h){if(a){var k=["MSG#",a,"#",b,"#",c,"#",e];this.l=a;this.type=b;this.v=c;this.j=e;this.g=d||[];this.o=k;this.D=g;this.C=h;if(d)for(let l of d)k.push(":",l||0);if(f)for(let l in f)if(parseInt(l)&&(g=l,a=f[l],null!=a&&!this.m))switch(b=this.o,c=this.D,d=this.C,e=c&&d,d=d?"/":":",h=a instanceof String?"string":typeof a,b.push(",",g,"="),h){case "string":b.push(kb(a),":",a);break;case "number":b.push(a);break;case "boolean":b.push(a?1:0);break;case "object":if(a instanceof Array){g=
b.length;k=h=0;for(let m of a)m instanceof ArrayBuffer||m instanceof Uint8Array?(c?(m=qa(m),h+=m.length):h+=m.byteLength,++k):(m=m.toString(),h+=kb(m)),b.push(m);k&&e?(a=btoa(b.splice(g).join("")),b.push(a.length,"%",a)):b.splice(g,0,h,k?d:":")}else a instanceof ArrayBuffer||a instanceof Uint8Array?e?(a=btoa(qa(a)),b.push(a.length,"%",a)):c?(a=qa(a),b.push(a.length,":",a)):b.push(a.byteLength,d,a):a instanceof Blob&&b.push(a.size,d,a)}}else this.u=new FileReader}
function lb(){this.g=lb.prototype.A++}lb.prototype.A=1;function mb(a,b,c,e){this.id=a;this.port=b;c&&(this.h=c=c.toLowerCase(),this.i="iframe"==c);e&&(this.j=e)}mb.prototype.g=0;function L(a,b){return`${a},${b}`}function nb(a,b,c){this.id=L(b,a);this.i=null==c||0>c?null:L(b,c)}function ob(){}function pb(a){a.m||(a.o.push(";"),a.m=!0);return new Blob(a.o)}function qb(a,b,c){a.m?a.h(a):(b.g=c||0,b.h=0,a.u.onload=a.A.bind(a,b),rb(a,b,0,50))}
jb.prototype.A=function(a){for(var b=this.u.result;;)switch(a.h){case 0:var c=b.search(fb);if(0>=c)return this.h(this);var e=b[c],d=b.slice(0,c++).split("#",6);if(5!=d.length||"MSG"!=d[0])return this.h(this);this.l=parseInt(d[1]);this.type=parseInt(d[2]);this.v=parseInt(d[3]);this.j=parseInt(d[4]);b=b.slice(c);a.g+=c;a.h=":"==e?1:","==e?2:5;break;case 1:c=b.search(gb);if(0>=c)return c?rb(this,a,b.length,100):this.h(this);e=b[c];d=this.g=b.slice(0,c++).split(":");for(var f=0;f<d.length;f++){let g=
d[f];d[f]=g.includes(".")?parseFloat(g):parseInt(g)}b=b.slice(c);a.g+=c;a.h=","==e?2:5;break;case 2:c=b.search(fb);if(0>=c)return c?rb(this,a,b.length,25):this.h(this);e=b[c];f=b.slice(0,c++).split("=",3);if(2!=f.length)return this.h(this);d=parseInt(f[0]);f=parseInt(f[1]);a.g+=c;if(":"==e){a.j=d;a.i=f;a.h=3;b=a;a=a.i;c=b.g;b=b.slice(c,c+a);b.size==a?this.u.readAsText(b):this.h(this);return}this[d]=f;b=b.slice(c);a.h=","==e?2:5;break;case 3:return this[a.j]=b,a.g+=a.i,a.h=4,rb(this,a,0,21);case 4:switch(b[0]){case ",":a.h=
2;b=b.slice(1);break;case ";":a.h=5;break;default:return this.h(this)}a.g++;break;case 5:this.m=!0;this.s(this);a.size>a.g&&(b=new jb,b.s=this.s,b.h=this.h,qb(b,a,a.g));return}};function rb(a,b,c,e){let d=b.g;c=d+c;b.size>c?a.u.readAsBinaryString(b.slice(d,c+e)):a.h(a)}
function N(){let a=this.constructor.prototype;for(let b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.s=0;this.G=null;this.W=this.ra=0;this.Pa=1;this.C=null;this.Pb=Ea.version||"";this.Ra="";this.ma=0;this.ka=!1;this.M=null;this.P=!1;this.I=this.H=null;this.xa=this.v=!1;this.Sa=!0;this.Ma=this.O=null;this.Qa=this.ga=this.oa=!1;this.Nb=1;this.Aa=this.u=this.V=null;this.Ca=1;this.Ta=0;this.N=this.L=null;this.Na=Ja;this.$=[];this.ya=0;this.Oa=null;this.Da=this.na=!1;this.A=
null;this.sa=Array(16);this.i={};this.m={};this.g={};this.D={};this.h={};this.X={};this.l={};this.j={};this.qa={};this.ea={};this.o={};this.pa={};this.fa={};this.fa.Qb=[];this.Ia=[];sb(this,!1);browser.browserAction.onClicked.addListener(this.gb);browser.runtime.onMessage.addListener(this.kb);browser.windows.onCreated.addListener(this.$a);browser.windows.onRemoved.addListener(this.ab);browser.windows.onFocusChanged.addListener(this.Lb);browser.windows.onBoundsChanged&&browser.windows.onBoundsChanged.addListener(this.Kb);
browser.tabs.onActivated.addListener(this.Bb);browser.tabs.onUpdated.addListener(this.Eb);browser.tabs.onAttached.addListener(this.Cb);browser.tabs.onRemoved.addListener(this.Db);browser.webRequest.onBeforeRequest.addListener(this.hb,{urls:[browser.runtime.getURL("*")]},["blocking"]);tb(this);ub(this)}n=N.prototype;n.kb=function(a,b){switch(a[0]){case 38:a[1]&&this.ka&&browser.storage.local.set({silent:!0});browser.tabs.remove(b.tab.id);break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};
n.gb=function(a){if(this.Qa){if(this.fb)return browser.windows.update(this.fb,{focused:!0});var b=a.id,c=this.o[b];sb(this,c,b,!0);this.ga&&(c?(this.da(a.windowId),vb(this,b)):wb(this,b))}};function sb(a,b,c,e){c?a.o[c]=!b:a.Qa=b||e;xb(b,c,e)}
function xb(a,b,c){if(c||!b||!a){var e=a?Ga:Ha;browser.browserAction.setTitle({title:a?yb+zb:b?Ab+zb:c?Ab:Bb,tabId:b});browser.browserAction.setIcon({path:e,tabId:b});a||browser.browserAction.setBadgeBackgroundColor({color:"#606060"});browser.browserAction.setBadgeText({text:a?"":"X",tabId:b})}}
function Cb(a,b){a.v&&(browser.downloads.setUiOptions||browser.downloads.setShelfEnabled(!b));if(b){a.v&&a.K(3,browser.downloads.onCreated,a.ib);a.v&&a.K(3,browser.downloads.onDeterminingFilename,a.jb);b=["blocking"];const c=Ca?[]:["extraHeaders"];a.K(4,browser.webRequest.onBeforeRequest,a.Za,{urls:Oa,types:Ka},b);a.K(4,browser.webRequest.onBeforeRequest,a.Za,{urls:K,types:Na},["requestBody"]);a.K(4,browser.webRequest.onBeforeSendHeaders,a.Gb,{urls:K,types:Na},["requestHeaders"].concat(b,c));a.K(4,
browser.webRequest.onHeadersReceived,a.Ib,{urls:K,types:Na},["responseHeaders"].concat(b));a.K(4,browser.webRequest.onResponseStarted,a.Jb,{urls:K,types:Na});a.K(4,browser.webRequest.onErrorOccurred,a.Hb,{urls:K,types:Na})}else a.Ja(3,4)}
n.Ya=function(a){browser.runtime.lastError;if(a){var b=a.value;a=ya[b.mode];var c,e;this.sa.fill(void 0);if(5==a&&(e=b.pacScript))e.data&&5E4<e.data.length?a=4:(c=e.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=e.url,this.sa.fill(!0);else if(7==a){b=b.rules;e=b.bypassList;c=Db(this,b.singleProxy);if(!c){c=Db(this,b.fallbackProxy);let d=Db(this,b.proxyForHttp,1),f=Db(this,b.proxyForHttps,9);b=Db(this,b.proxyForFtp,2);d!=f||d!=b||d!=c&&c?(c=`${d??""};${f??
""};${b??""};${c??""}`,++a):c=d}e&&e.length&&(c+=";"+e.join(","))}b=5>a?a.toString():c?`${a}:${c}`:null;b!=this.A&&(this.A&&Eb(this),this.A=b)}};function Db(a,b,c){if(b){let e=b.scheme||"http",d="https"==e;a=a.sa;c?a[c]=d:a.fill(d);if(xa(e))return`${e}://${b.host}${b.port?":":""}${b.port||""}`}}
async function Eb(a){if(a.s){var b=a.L;if(!b){var c=1==a.s?(new URL(a.G.url)).host:Ia[0];c="http://"+c;b=c+"/status/204+IDM"}var e=AbortSignal.timeout(1E3);(e=await pa(b,{cache:"no-cache",signal:e}))&&204==e.status?c&&(a.N=a.M?c+"/client/"+a.M:null,a.L=b):a.L=a.N=null}}n.wa=function(a,b,c,e){let d=this.l;return b in d?d[b]:d[b]=new mb(b,a,c,e)};
function Hb(a,b,c,e,d){let f,g,h;E(b)?(f=b.frameId??0,g=b.parentFrameId,h=b.method&&b.id,c||=b.tabId,d||=b.url):f=b;let k=a.D[L(c,f)];k||(k=new nb(f,c,g),a.D[k.id]=k);h?(k.l!=h&&(k.l=h,k.v=d,k.j=!1,k.h&&(k.h=d.startsWith(b.initiator||b.originUrl))),k.s="POST"==b.method):d&&(d.startsWith("about:blank")?f&&(k.h=!0):k.B=d);null!=e&&(k.o=e);return k}function Ib(a,b){return a.D[L(b.tabId,b.frameId)]}function Jb(a){let b=new lb;return a.X[b.g]=b}
function Kb(a,b){let c;b instanceof lb?c=b.g:b=a.X[c=b];delete a.X[c];return b}function Lb(a,b){for(let c of a.$)if(c&&c[101].test(b))return c.U;return 0}
n.za=function(){var a=this.ra%(Ia.length+1);a<Ia.length?(a=this.G=new WebSocket(`ws://${Ia[a]}/?cid=${this.M||0}&rnd=${D().toString().substr(2,9)}`,"plugin.v3.internetdownloadmanager.com"),a.onerror=O,a.onopen=this.Ga,a.onclose=this.ia,a.onmessage=this.Ab,1==a.readyState?this.Ga(1):3==a.readyState?this.ia():this.C=J.setTimeout(this.ia,1500,a)):(a=this.G=browser.runtime.connectNative("com.tonec.idm"),a.onDisconnect.addListener(this.ia),a.onMessage.addListener(this.ob),this.C=J.setTimeout(this.Ga,0,
2))};n.Ga=function(a){this.C&&(J.clearTimeout(this.C),this.C=null);this.s=E(a)?1:a;this.Pa=1;this.ka=!1;a=browser.i18n.getUILanguage().replace("_","-");"sr"==a&&(a+="-Cyrl-CS");P(this,2,5,1024,[111,85,1031,0,16845059,this.M,0,Ea.manifest_version],{[112]:Ba,[113]:Aa,[116]:a})};
n.ia=function(a){this.C&&(J.clearTimeout(this.C),this.C=null);var b=browser.runtime.lastError||a&&a.error,c=this.G;if(c instanceof WebSocket){if(a===c)return c.close()}else c&&ib(b&&b.message)&&(this.ka=!0);this.G=null;this.s&&(this.s=0,this.qa={},Cb(this,!1),this.Ja(1,2),this.ga=!1,this.A=this.N=this.L=null,sb(this,!1));a=++this.ra;b=Ia.length+1;c=a/b;120>c&&(1==c&&Mb(this),!a||a%b?this.za():J.setTimeout(this.za,5E3*c))};
n.Va=function(){let a=this.G;a instanceof WebSocket?a.close():a&&(a.disconnect(),this.ia())};n.Ab=function(a){let b=new jb;b.s=this.Wa;b.h=this.Va;qb(b,a.data)};n.ob=function(a){let b=new jb;b.s=this.Wa;b.h=this.Va;qb(b,new Blob([a]))};
function P(a,b,c,e,d,f,g){let h=a.W,k=a.s;if(!k)return 0;let l=a.Pa++;b=new jb(l,b,c,e,d,f,2==k,99<=h);if(g)return g.open("POST",`${a.N}?seq=${l}`,!1),g.send(pb(b)),200==g.status?l:0;if(1==k)a.G.send(pb(b));else try{var m=a.G,p=m.postMessage;b.m||(b.o.push(";"),b.m=!0);p.call(m,b.o.join(""))}catch(q){return a.ia(),0}e&1&&(a.qa[l]=b);return l}
function Nb(a,b){if(b.g){var c=b.g[1],e=a.j[c];if(e)return e.h?b.i=e.port.id:null;e=a.m;for(var d in e)if(e[d].l==c)return b.i=d}c=b[6];d=b[17];e=b[50];let f=b[7];var g=a.fa;let h=a.l;a=a.g;let k,l,m;if((k=g[c])||(k=g[d]))return b.i=k.id;if(k=g[e])m=k.id;for(let p in h){g=h[p];let q=g.j;if(q){if(q==c||q==d||q==e){k=g.port;if(f){let r=a[k.tabId];r&&r.B!=f&&(k=null)}if(k)return b.i=k.id}q==f&&(l=g.port.id)}}return m?b.i=m:l?b.i=l:null}
function Ob(a,b){let c=b.i;if(c)return c;if(b.g){var e=a.g[L(b.g[6],b.g[7])];e?c=e.id:(e=b.g[7])&&a.m[e]&&(c=e)}if(c||=Nb(a,b))return b.i=c;e=a.m;let d=b[50],f=b[7];for(let g in e){let h=e[g];if(h.B==d)return b.i=h.id;h.B==f&&(c=h.id)}return c?b.i=c:f?F(browser.tabs.query({url:f},G())).then(g=>g?.length&&(g=a.g[g[0].id])?b.i=g.id:null,()=>null):null}
async function Pb(a,b){var c=b.tabId;let e=b.aa;if(0<e&&!b.i){var d=await F(browser.webNavigation.getFrame({frameId:e,tabId:c},G()));d&&(d=d.parentFrameId,0<=d&&(b.i=L(c,d)))}if(null!=e&&b.s){if(d=a.D[L(c,e)]){b.l=d.l;b.m|=d.j;b.j|=d.o;b.A=d.h;let f=d.ba;f&&b.B!=f&&(b.ba=f);b.i||(b.i=d.i);(d=a.j[b.l])&&!d.port&&(d.port=b)}a.g[L(c,e)]=b;d=b.U;c=[11,a.W,b.id,c,e,d,b.j,b.m,a.i[22],a.i[23],hb[a.xa?1:null]];d&&b.m&&(a=a.$[d],c.push(hb[a.eb]),fa(c,a.bb.map(la(a)).map(ra)));b.postMessage(c)}}
n.ja=async function(a,b,c,e,d,f){var g=Q(a);if(g){var h=0<(g&32),k=1==(g&=7),l;k&&!h&&(l=await R(a));g=[g];a={[6]:Qb(a,k&&this.P),[50]:b,[7]:c,[8]:e,[100]:d,[102]:f,[51]:T(l),[54]:navigator.userAgent,[121]:this.A};P(this,14,1,0,g,a)}};
async function Rb(a,b,c){if(b&&b.length){var e=b.map(k=>R(k[0]));if(c){var d=c.i;var f=c.N;var g=c.s;d&&!f&&e.push(R(d))}e.length&&(e=await Promise.all(e),b.forEach(k=>k[5]=T(e.shift())),e.length&&(f=T(e.shift())));c=0;var h=[0,0,0];d={[8]:4,[54]:navigator.userAgent,[7]:d,[110]:g,[111]:f,[121]:a.A};1<b.length&&(h[1]=P(a,15,1,0,[b.length],d),c=16,d={});for(let k of b)h[2]++,d[6]=k[0],d[100]=k[2],d[102]=k[3],d[50]=k[4],d[51]=k[5],P(a,14,2,c,h,d)}}
n.Ba=function(a,b){if(!this.s)return Sb("cannot_contact_idm");let c=a.linkUrl,e=a.pageUrl,d=e,f=this.g[L(b.id,a.frameId)];if(a.menuItemId==this.pa[5])return browser.downloads.search({query:[c]},this.cb.bind(this,c));if(a.menuItemId==this.pa[2]){if(c=a.frameUrl,c&&"about:blank"!=c||(c=e,d=null),this.H&&f?.U)return Tb(this,!0)}else if(!c){c=a.srcUrl;if(!Q(c)){if(this.H&&f?.U&&"video"==a.mediaType)return Tb(this,!0);return}if(f&&c)return a=Jb(this),a.tabId=b.id,a.port=f,a.o=c,a.u=d,a.i=e,a.m=4,f.postMessage([18,
a.g,c])}this.ja(c,d,e,4)};n.La=function(a,b){if(!this.s)return Sb("cannot_contact_idm");Ub(this,b.id,a.menuItemId==this.pa[3])};n.cb=function(a,b){let c,e,d;for(;c=b.pop();)c.exists&&"complete"==c.state?e||(d||=c.referrer):(e||=c.referrer,browser.downloads.erase({id:c.id}));this.ja(a,e||d,null,4)};
function Ub(a,b,c,e,d,f,g,h,k){if(!e||a.i[-5]){var l=a.g[b];if(l){var m=Jb(a);m.tabId=b;m.port=l;m.M=c;m.P=d;m.h=0;m.j=[];if(l=e&&!!f)m.I=!0,m.L=f,m.C=g,m.D=h,m.v=k,f.h||Vb(a,f);f=m.g;(e=e&&a.i[12])?(e=e.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),e=`${"^(?:http|https|ftp|ftps)://"}(?:[^\\/]*@)?(?:${e})(?::\\d+)?(?:\\W|$)`):e="^(?:http|https|ftp|ftps)://";m.l=Wb(a,b,[12,f,c,l||d,e]);m.G=0;m.l||Kb(a,m)}}}
n.Ob=function(a,b,c,e,d,f,g,h){if(a=this.X[b]){e&&(a.h+=e);g&&(a.i=g);h&&(a.s=h);if(d&&("string"==typeof d&&(d=JSON.parse(d)),d instanceof Array)){if(f)for(let k of d)k[4]=f;fa(a.j,d)}++a.G<a.l||(a.I?(e=a.tabId,(d=this.h[a.port.g])&&d.J==e&&a.h&&(f=a.v,g=d.h,h=d.i,P(this,10,1,0,[4294967295,d.v,Math.round(a.C*f+(d.l+g)*h),Math.round(a.D*f+(d.G+g)*h),0,a.h]),this.u=e,Wb(this,e,[13,!0]))):(e=a.j,e.length?Rb(this,e,a):Sb("cannot_find_links")),Kb(this,a))}};
n.sb=function(a,b,c,e){(a=Kb(this,b))&&this.ja(a.o,a.u,a.i,a.m,c,e)};n.ib=function(a){if((this.v||a.byExtensionId)&&!this.Da&&this.i[-6]){var b=a.finalUrl||a.url;if(Q(b,!0)){var c=a.id,e=Date.parse(a.startTime),d;for(d of v(this.j))if(b==d.url&&e>=d.X&&50>e-d.X)break;if(d&&(d.Ka=c,a.request=d,this.o[d.tabId]))return;this.ea[c]=a;browser.downloads.pause(c,O)}}};
n.jb=function(a,b){var c=a.id;let e=this.ea;var d=e[c];if(d){var f=this.i,g=d.request;d=a.finalUrl||(a.finalUrl=a.url);var h=g?g.va:new URL(d),k=g?g.S:a.S=Q(d,!0),l=g?g.ha:a.ha=U(a.filename||h.pathname);if(!((g?g.na:a.l=this.na)||this.v||f[1].test(l)&&!f[9].test(h.hostname)&&!f[19].test(h.href)))return Xb(this,c);a.request=g;a.Rb=b;e[c]=a;if(g)return V(this,2,g,null,a)?a.Ea=!0:Xb(this,c);if(1==k){if(!a.referrer){b=this.h;for(var m of v(this.m))if(m.B==d&&(a.referrer=m.D,(c=b[m.g])&&c.J==m.tabId))break}m=
R(d);d=d==a.url?null:R(a.url);Promise.all([m,d]).then(p=>Yb(this,a,...p));return a.Ea=!0}return Yb(this,a)}};function Yb(a,b,c,e){var d=Date.parse(b.startTime)||Date.now();d=[b.id,0,C(d),0,b.S,2];c={[6]:Qb(b.finalUrl,a.P),[4]:b.ha,[103]:b.totalBytes||null,[100]:b.filename||null,[127]:b.mime||null,[8]:b.l?2048:0,[50]:b.referrer||null,[51]:T(c),[54]:navigator.userAgent,[122]:a.A};b.finalUrl!=b.url&&(c[17]=Qb(b.url),c[56]=T(e));return!!P(a,13,1,129,d,c)||Xb(a,b.id)}
function Xb(a,b,c){let e=a.ea[b];if(e){delete a.ea[b];let d=e.request;d&&(d.Ka=null,d.Fa&&W(a,d));if(c)return browser.downloads.cancel(b,O),!0;e.Ea&&(e.Ea=!1,e.Rb());browser.downloads.resume(b,O)}}n.vb=function(a,b,c,e,d,f){this.wa(a,b,c,e);P(this,23,2,0,[b,a.tabId,a.l,a.U,a.aa],{[132]:e,[133]:d,[134]:f})};
n.Y=function(a,b,c){if(4294967295==a)this.u=null,c=!0;else{let e=this.l[a];if(e){c=e.g;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.g=3;J.setTimeout(this.Y,1E3,a,!1,!0);return}e.g=0;c=!0}}c&&P(this,8,1,32,[a])};
n.Vb=async function(a,b,c,e,d,f,g,h,k,l){let m=a.tabId,p=a.g;var q=this.h[p];let r=this.o[m];if(b){var t=Kb(this,b);if(t=t&&t.H){if(!c&&a.A){let H=this.g[a.i];if(H)return H.postMessage([15,b,null,t[6],t[17],t[50],t[31],t[133],t[134]])}var u;b={};if(!e){if(!c||null==d){if(!a.h){c=a.la;f="iframe";g=a.B;var z=!!c}if(!z){c=m;f=g=null;var x=!0}}a=this.wa(a,c,f,g);q=m==q.J&&!q.R&&(x||z||d)&&!r;!q||x||a.g||J.setTimeout(this.da,3E3,p);var y=2;a.g=q?1:2;var S=(q?128:64)|(x?512:0);!h&&(u=this.g[m])&&(h=u.C)}h&&
(b[101]=h,b[128]=k);l&&(b[137]=l);await X(this,t,y||1,S||0,p,m,c,b);!y||x||r||Zb(this,c,d)}}else e?(this.Y(c,!0),delete this.l[c]):m!=q.J||q.R||r||(d?Zb(this,c,d,!0):$b(this,c))};function ac(a,b){let c=a.h[b];if(c&&c.g){var e=c.h,d=c.i;P(a,7,2,c.R?128:c.A?256:c.j?512:0,[b,Math.round((c.l+e)*d),Math.round((c.G+e)*d),Math.round((c.width-e-c.H)*d),Math.round((c.height-e)*d)])}}
function Zb(a,b,c,e){let d=a.l[b];if(d&&d.g){var f=d.port;let g,h=256;2==d.g&&(null==e&&(g=a.h[f.g])&&(e=f.tabId==g.J&&!g.R),e?(h|=128,d.g=1):h|=64);(e=d.i)&&!c&&(c=f.o);let k,l,m,p,q,r;if(c){k=c[0];l=c[1];m=c[2]||k+1;p=c[3]||l+1;q=c[4];if(c=!e&&f.o)k+=c[0],l+=c[1],m=Math.min(m+c[0],c[2]),p=Math.min(p+c[1],c[3]);if(f=a.g[f.tabId])r=f.L}P(a,9,1,h,[b,k,l,m,p,q,r])}}
n.da=function(a){var b=this.o;let c=this.g;var e=this.h;let d=a?[e[a]]:v(e);a=[];e={};for(var f of d)!f||f.R||f.ca||b[f.J]||a.push(f.J);if(a.length)for(let g of v(this.l))g.g&&(b=g.port,f=b.tabId,a.includes(f)&&((f=b.h?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),g.h?b.h?b.postMessage([15,null,g.id]):Vb(this,b,null,e):Zb(this,g.id,null,!0)))};function bc(a,b){let c=a.h,e;if(b=null==b?v(c):(e=c[b])?[e]:null)for(e of b)wb(a,e.J)}
function wb(a,b,c,e){e=0!=e;let d=c?0:2;c=c?32:64;for(let f of v(a.l))f.g&&f.port.tabId==b&&f.g!=d&&(e||f.h)&&(f.g=d,P(a,8,1,c,[f.id]))}function $b(a,b){let c=a.l[b];c&&1==c.g&&(c.g=2,P(a,8,1,64,[b]))}function cc(a,b,c,e){var d=a.ya;let f=(d&b)!=((c?255:128)&b);a.ya=c?d|=b:d&=~b;f&&(c=a.i[-32],b=a.i[-33],c=a.na=0!=c&&(d&c)==c,d=a.Da=0!=b&&(d&b)==b,a.Oa=(c||d)&&e||null)}
n.Ha=function(a,b,c,e,d){let f=this.h[a];if(f)if(f.ca?e&&(J.clearTimeout(f.ca),f.ca=null):e||=-1,0<=e)f.o|=b,f.s|=c,e&&(f.ca=J.setTimeout(this.Ha,e,a));else{b|=f.o;c|=f.s;f.o=f.s=f.ca=null;if(b){for(let g of v(this.m))g.h&&g.g==a&&(g.update=!0);d?this.Z(d):browser.windows.get(a,this.Z);browser.tabs.query({windowId:a,active:!0},this.Z)}if(c){if((a=this.h[a])&&!a.R&&!a.ca&&(a=a.J,!this.o[a])){b=this.l;for(let g in b)c=b[g],c.g&&c.port.tabId==a&&1==c.g&&P(this,8,1,1152,[g])}}else this.da(a)}};
n.Z=function(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,e=this.h[c];if(e){var d=!a.windowId;if(d){b&&(e.i=this.Ca);var f=e.j="minimized"==a.state,g=e.A="maximized"==a.state;f||(e.width=a.width,e.height=a.height,e.m=a.left,e.u=a.top,f=e.R,a=e.R="fullscreen"==a.state,g=g&&-e.m,0<g&&16>=g&&g==-e.u&&(e.h=g),a==f||b||(a?bc(this,c):this.da(c)))}else a.active&&(e.J=a.id),a.width&&(e.D=a.width),a.height&&(e.C=a.height);if(!e.j){a=e.width;let h=e.D;g=e.height;
f=e.C;let k=h>a||f>g;if(k||!h||!f){d||k&&browser.windows.get(c,this.Z);return}d=a-h;a=d/2;0<=a&&16>=a?(e.h=a,e.l=e.H=0):(a=e.h,e.l=d-2*a);d=g-f-2*a;d>=(e.I?20:40)&&150>=d&&(e.G=d)}b||ac(this,c);return e}}};function vb(a,b){return a.o[b]?!0:(a=a.g[b])&&a.j?(a.j=!1,browser.tabs.reload(b),!0):!1}n.Sb=function(a,b,c,e){a.B=b;a.D=c;a.j&&!e&&(a.j=!1);null==a.aa&&Pb(this,a);this.da(a.g);0<this.H&&a.h&&1==a.U&&(this.i[11]?.test((new URL(b)).hostname)||Tb(this))};
n.Ub=function(a,b,c,e,d){a.C=b;a.L=d;a=[a.l,a.tabId,a.g,e,d];e={};e[110]=b;e[128]=c;P(this,21,1,0,a,e)};
n.Wb=function(a,b,c,e,d){let f=a.tabId,g=this.g[L(f,c)];if(g){var h=g.o;g.la=e;if(g.o=d){var k=a.o;k&&(d[0]+=k[0],d[1]+=k[1],d[2]=Math.min(d[2]+k[0],k[2]),d[3]=Math.min(d[3]+k[1],k[3]));if(h&&h.join()!=d.join()){h=this.g;a=L(a.tabId,"");c=a+c;for(let l in h)l.startsWith(a)&&(k=h[l],k.i==c&&g.postMessage([16,b,k.aa,k.la]))}}if(!this.o[f]){Zb(this,e,d);for(let l of v(this.l))l.port==g&&l.g&&l.h&&!l.i&&g.postMessage([15,null,l.id])}}};
function Vb(a,b,c,e){var d=a.g;c=[16,c];a=[b];for(let f;f=d[b.i];b=f){if(e)if(e[b.id])break;else e[b.id]=!0;a.push(f)}for(e=a.pop();b=a.pop();e=b)d=b.la,c[2]=b.aa,c[3]=d,c[4]=d?null:b.B,c[5]=d?null:b.ba,e.postMessage(c)}function Wb(a,b,c){a=a.g;b=L(b,"");let e=0;for(let d in a)d.startsWith(b)&&(a[d].postMessage(c),e++);return e}
n.ta=function(a,b){let c={file:"content.js",runAt:"document_start",matchAboutBlank:!0};b?c.frameId=b:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();){if(!b.discarded)try{browser.tabs.executeScript(b.id,c,O)}catch(e){}}else if(b=a)try{browser.tabs.executeScript(b.id||b,c,O)}catch(e){}};function dc(a,b,c,e){null==c&&(c=b.v==a.V);P(a,6,2,17|(c?2048:1024)|(b.A?256:b.j?512:0),[b.v,b.g,b.width,b.height,b.m,b.u,b.i],{[117]:e})}
async function ub(a){var b=F(browser.windows.getAll({windowTypes:["normal","popup","app"]},G())),c=F(browser.tabs.query({active:!0},G()));[b,c]=await Promise.all([b,c]);let e={};if(c)for(let d of c)e[d.windowId]=d;for(let d of b)b=e[d.id],c=a.Z(d,!0)||a.$a(d,!0,b),dc(a,c,d.focused,d.title||b&&b.title)}async function ec(a){await fc("system.display")&&(a.Ta=(await F(browser.system.display.getInfo(null,G())))[0].displayZoomFactor)}
n.wb=function(a){let b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.Nb++);var e=b.id,d="top"==a.name;a.tabId=e;a.g=0>b.index?null:b.windowId;a.s=!0;a.v=!1;a.update=d;a.h=d;a.aa=d?0:a.sender.frameId;a.M=0;a.B=a.sender.url||d&&b.url||null;a.ba=null;this.m[c]=a;d&&(this.g[e]=a);a.B&&(a.U=Lb(this,(new URL(a.B)).hostname));a.onMessage.addListener(this.xb.bind(this,a));a.onDisconnect.addListener(this.ua);Pb(this,a)}};
n.ua=function(a){browser.runtime.lastError;if(a.s){a.s=!1;var b=L(a.tabId,a.aa),c=this.X,e=this.l,d,f=this.fa,g=this.j,h;for(let k in c)c[k].port===a&&delete c[k];for(let k in e)if(d=e[k],d.port===a)this.Y(k),delete e[k];for(let k in f)f[k]===a&&delete f[k];for(let k in g)(h=g[k],h.port!==a||h.j)||delete g[k];this.Oa===a&&cc(this,255,!1);delete this.m[a.id];delete this.g[b];a.h&&delete this.g[a.tabId];a=this.D;for(let k in a)b==a[k].i&&delete a[k]}};
n.xb=function(a,b){let c=b.shift();b.unshift(a);switch(c){case 21:this.Sb.apply(this,b);break;case 24:this.Ub.apply(this,b);break;case 22:this.Wb.apply(this,b);break;case 23:this.Vb.apply(this,b);break;case 41:this.vb.apply(this,b);break;case 25:this.wa.apply(this,b);break;case 26:Ub(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.Ob.apply(this,b);break;case 28:this.Y(4294967295);break;case 29:this.Ua.apply(this,b);break;case 30:this.Ua.apply(this,b);break;case 31:this.qb.apply(this,b);
break;case 32:this.tb.apply(this,b);break;case 39:this.rb.apply(this,b);break;case 33:this.lb.apply(this,b);break;case 34:this.pb.apply(this,b);break;case 35:this.sb.apply(this,b);break;case 36:this.Mb.apply(this,b);break;case 37:this.zb.apply(this,b);break;case 46:this.nb.apply(this,b)}};
n.Wa=function(a){let b=a.type,c=a.v;var e=a.j,d=a.g,f;if(1==b){let p=d[0];if(f=this.qa[p])b=f.type,delete this.qa[p]}switch(b){case 3:0<=this.ra&&(this.ra=-1,Eb(this));var g=d[5],h=d[6],k=d[4],l=d[8];this.W=d[0];gc(this,h);hc(this,g,a);ic(this);if(k||l)l=(k?k/96:1)*(l?l/100:1),this.Ca=1.245>l?1:l,ub(this),this.Ta&&ec(this);Mb(this);break;case 4:g=this.i;this.v=!!(d[3]&2147483648);this.xa=!!(d[3]&1073741824);hc(this,d[2],a);ic(this);e&2048&&(J.idm=this);g[-6]=0<(e&64);g[-10]=0<(e&1024)||!1;g[-5]=0<
(e&32);g[-1]=0<(e&2);g[-8]=0<(e&256)||2>c;g[-9]=0<(e&512)||2>c;g[-32]=d[0];g[-33]=d[1];g[12]=a[12];g[17]=a[17];g[23]=a[23];109>this.W?g[23]=Va:110>this.W&&(g[23]+=sa("|Erfcbafr|hey|trg"));Y(g,a,1);Y(g,a,2);Y(g,a,3);Y(g,a,4);Y(g,a,10);Y(g,a,9,2);Y(g,a,11,2);Y(g,a,20);Y(g,a,21,1);jc(g,a,19);jc(g,a,18,1,1);a=this.i;g=this.pa={};browser.contextMenus.removeAll();for(d=1;d<kc.length;d++)h=kc[d],h[0]&&a[h[1]]&&(g[d]=browser.contextMenus.create({onclick:h[4].bind(this),title:lc(h[2]),contexts:h[3].split(","),
documentUrlPatterns:h[5]||Pa,enabled:!0}));this.ga||(this.ga=!0,sb(this,!0),this.K(1,browser.runtime.onConnect,this.wb),this.K(1,browser.proxy.settings.onChange,this.Ya),browser.proxy.settings.get({},this.Ya),this.K(1,browser.webNavigation.onCreatedNavigationTarget,this.ub),this.K(1,browser.webNavigation.onCommitted,this.Xa),this.K(1,browser.webNavigation.onHistoryStateUpdated,this.mb),(a=this.i[17])&&this.K(2,browser.webRequest.onBeforeRequest,this.Fb,{urls:a.split("|"),types:Ka},["blocking"]),Cb(this,
!0),browser.tabs.query({url:K},this.ta));break;case 18:g=d[0];d=d[1];f=I[d?-d:g];if(!f)break;d=this.$[g]={};e=f[2];d.U=g;d.eb=f[0];d.bb=f[1];for(h in a)(h=parseInt(h))&&(102==h||110<h&&150>h)&&(d[h]=e.includes(h)?RegExp(a[h]):a[h]);for(k of e){var m=void 0;(l=d)[m=k]||(l[m]=Ja)}g=this.$.map(ma(102)).filter(aa);this.Na=RegExp("^https?://(?:"+g.join("|")+")","i");Y(d,a,101,2);break;case 5:mc(this,d[0],e,d[1]);break;case 6:if(e&4)break;mc(this,f.g[0],e,d[2],d[1]);break;case 8:a=d[0];g=e&32;if(4294967295==
a)Wb(this,this.u,[13,!1]),this.u=null;else if(a=this.l[a])a.g=g?0:2;break;case 11:4294967295==d[0]&&(Ub(this,this.u,!0,!0),this.u=null);break;case 12:try{let p=a.g[5];g=4==p?2:3;if(1==p||2==p){if(Nb(this,a)){let q=a[4];if(this.i[3].test(q))1==p?g=6:p=4;else if(this.i[-1]||this.i[4].test(q))g=6;a[8]|=256}if(3==g){let q=this.h[this.V];q&&this.o[q.J]&&(g=1)}}if(4!=p)X(this,a,g);else{switch(a.g[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}nc(this,a)}}catch(p){X(this,
a,0)}break;case 13:a=f.g[0];h=f.g[5];d=d[1];k=3==d;if(3>=h)f.j&128?Xb(this,a,k):W(this,a,k);else if(5==h)if(d){if(d=(m=this.j[a])&&m.m){h=m.url;k=m.method;l=m.requestHeaders;if(a=m.i)(a=oc(a,l))?a=new Blob(a):k="GET";d.timeout=1E4;d.onreadystatechange=this.yb.bind(this,d,m.id);d.open(k,h,!0);for(g of l)h=g.name,k=h.toLowerCase(),k.startsWith("x-idm-")||(na(k)&&(h=`x-idm-${h}`),d.setRequestHeader(h,g.value));d.send(a)}}else pc(this,a);break;case 20:g=!a[123];a=[a.l];d={};d[121]=this.A;P(this,1,2,g?
2:4,a,d);break;case 24:qc(this,a);break;case 22:rc(d[0],d[1],a[131],a[130]);break;case 100:e&1&&P(this,100,1,0,[a.l],a);break;default:e&1&&P(this,1,2,0,[a.l])}};async function rc(a,b,c,e){null==Fa&&(Fa=await fc("notifications")||!1);Fa&&(browser.notifications.create(a.toString(),{type:"basic",title:e??"",message:c,iconUrl:"images/logo48.png"},O),b&&J.setTimeout(browser.notifications.clear,1E3*b,a.toString(),O))}
async function qc(a,b){let c=await R(b[6],!!(b.j&16));b=[b.l,c?c.length:0];let e={[51]:T(c)};P(a,1,2,c?2:4,b,e)}
async function nc(a,b){try{let g,h=b.i||b.g[2],k=b.g[8],l=a.l[k];if(l&&l.port)g=l.port;else if(h in a.m)g=a.m[h];else if(h=await Ob(a,b))g=a.m[h];else{let m=await F(browser.windows.getLastFocused(G()));if(m){let p=a.h[m.id];p&&(g=a.g[p.J])}}if(g){b.i=g.id;var c=a.h[g.g];if(c&&c.g){var e=a.g[g.tabId];e&&e.update&&(e.update=!1,e.postMessage([14,!0]));var d=Jb(a),f=[15,d.g,k];d.H=b;k||f.push(b[6],b[17],b[50],b[31],b[133],b[134]);g.h||Vb(a,g,d.g);g.postMessage(f)}else X(a,b,1)}else X(a,b,0)}catch(g){X(a,
b,0)}}async function X(a,b,c,e,d,f,g,h){-1!=c&&(e|=0==c?4:2,h||={},h[8]=b[8],d=[b.l,c,d,g,f,-1],b.j&32&&(3==c||2==c)&&(b=await R(b[6],!!(b.j&16)))&&(d[5]=b.length,h[51]=T(b)),P(a,1,2,e,d,h))}n.ub=function(a){Hb(this,a).g=!0};
n.Xa=function(a,b){var c=a.tabId,e=a.frameId;let d=a.url;var f=a.transitionType,g=a.frameType,h=a.documentId;let k="prerender"==a.documentLifecycle;this.O!=c||Wa(d)||(this.O=null);e&&k&&"outermost_frame"==g&&(e=a.frameId=0);f=f&&f.endsWith("_subframe");var l=!0;if(g=this.D[L(c,e)]){l=g.m;g.m=k?h:null;if(l&&l==h)return;h=g.u;l=!(d&&h&&(new URL(d)).hostname==(new URL(h)).hostname);g.u=d}else k&&(g=Hb(this,a),g.m=h);!f&&this.o[c]&&sb(this,l,c);if(h=this.g[L(c,e)])if(this.u&&(a=this.h[h.g])&&a.J==this.u&&
this.Y(4294967295),b){a:{b=h.B;c=new URL(b);e=new URL(d);if(c.origin==e.origin&&c.pathname==e.pathname)switch(Lb(this,c.hostname)){case 1:if("/watch"==c.pathname&&c.searchParams.get("v")==e.searchParams.get("v")){b=!0;break a}break;case 4:if((c.pathname.startsWith("/p/")||c.pathname.startsWith("/reel/"))&&c.searchParams.get("img_index")==e.searchParams.get("img_index")){b=!0;break a}}b=d==b}if(!b){b=this.l;var m;for(let p in b)if(m=b[p],m.port===h)2==h.U||4==h.U?$b(this,p):(this.Y(p),delete b[p]);
h.M++;h.B=d;h.h&&(h.update=!0);h.postMessage([17,!0])}}else this.ua(h,!0),f&&"about:blank"==h.B&&this.ta(c,e);else f&&"about:blank"==d?(Hb(this,a),this.ta(c,e)):g&&g.g&&(g.B||!b)&&(g.g=!1)};n.mb=function(a){return this.Xa(a,!0)};
n.$a=function(a,b,c){let e=a.id;c={v:e,width:a.width,height:a.height,m:a.left,u:a.top,i:this.Ca,h:8,G:66,l:0,H:0,I:"popup"==a.type||"app"==a.type,R:"fullscreen"==a.state,A:"maximized"==a.state,j:"minimized"==a.state,J:c&&c.id,C:c&&c.height,D:c&&c.width,g:null,ca:null};Object.setPrototypeOf(c,ob.prototype);this.h[e]=c;a.focused&&(this.V=e);b&&(browser.tabs.query({windowId:e,active:!0},this.Z),browser.tabs.query({windowId:e,url:K},this.Tb),browser.tabs.query({windowId:e,url:K},this.ta));return c};
n.Tb=function(a){for(let b of a)Hb(this,0,b.id,!0,b.url)};n.ab=function(a){P(this,5,1,32,[a]);delete this.h[a]};n.Lb=function(a){if(0<a){let b=this.h[a];b&&(this.V=a,b.g||dc(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.Z),vb(this,b.J))}else this.V=null};n.Kb=function(a){this.Ha(a.id,!0,!1,-1,a)};function mc(a,b,c,e,d){let f=a.h[b];f?(e&&(f.i=e),d&&(f.g=d),e=!!(c&128),f.R!=e&&(f.R=e)&&bc(a,b),(d||c&4096)&&ac(a,b)):a.ab(b)}
n.Eb=function(a,b,c){let e=c.active;c=c.windowId;let d=e&&this.h[c];d&&(d.g||dc(this,d));"complete"==b.status&&(a=this.g[a])&&!a.v&&(a.v=!0,e&&this.da(c))};n.Db=function(a){let b=this.g,c=this.D,e=L(a,"");this.O==a&&(this.O=null);let d=b[a];d&&this.ua(d,!0);for(let f in b)f.startsWith(e)&&this.ua(b[f],!0);for(let f in c)f.startsWith(e)&&delete c[f];delete this.o[a]};
n.Bb=function(a){let b=a.tabId;a=a.windowId;this.ya=0;this.u&&this.Y(4294967295);var c=this.h[a];c&&(wb(this,c.J),c.J=b,(c=this.O)&&b!=c&&this.s&&(this.O=null,J.setTimeout(browser.tabs.remove,250,c)),browser.tabs.get(b,this.Z),vb(this,b)||this.da(a))};n.Cb=function(a,b){b=b.newWindowId;for(let c of v(this.m))c.tabId==a&&(c.g=b);wb(this,a,!0)};
n.Ua=function(a,b,c){if(a.h){let e=a.tabId;a=a.g;let d=this.h[a];this.u&&this.Y(4294967295);if(d&&d.J==e){let f=!1;b&&(d.D=b,f=!0);c&&(d.C=c,f=!0);wb(this,e,!1,f);this.Ha(a,f,!1,500)}}else a.la&&(b=this.g[a.i])&&b.postMessage([16,null,a.aa,a.la])};n.qb=function(a,b,c){(b=ua[b])&&cc(this,b,c,a)};n.tb=function(a,b,c){0==b&&cc(this,128,c,a)};n.rb=function(a,b,c,e){this.Aa=a.id;a.H=b;a.G=c;a.I=e};n.lb=function(){cc(this,255,!1)};
n.pb=function(a,b,c,e){var d=a.l;d&&(a=32,d=[d,null==c?(a|=16,-2):c],P(this,16,1,a,d,{[110]:b,[115]:e}))};n.Mb=function(a,b,c){if(a=this.j[b])P(this,16,1,48,[a.id,0],{[115]:c}),a.A=!1,a.Fa&&W(this,a)};n.nb=function(a,b,c,e){null!=b&&(a.N=b?1:-1);null!=c&&(a.u=c?1:e?2:-1)};n.zb=function(a,b,c,e){P(this,19,2,0,[b,c,a.tabId,a.l],e)};n.yb=function(a,b){4==a.readyState&&(P(this,16,1,48,[b,0],{[115]:200==a.status?a.response:null}),pc(this,b))};
function pc(a,b){if(b=a.j[b]){var c=b.m;b.m=null;b.A=!1;b.Fa&&W(a,b);c&&c.abort()}}function sc(a,b){let c=a.i;if(b.u||a.o[b.tabId]||!c[-6])return 1;if(b.l)return 6;if(b.h&&c[-1])return 1;let e=b.va,d=b.N=U(e.pathname);return c[9].test(e.hostname)||c[19].test(e.href)?1:2==(b.S&7)&&(b.I||c[-10])?e.pathname.endsWith("/")||c[21].test(e.pathname)?1:c[1].test(d)||a.v&&!c[20].test(d)?4:1:6}
function tc(a,b){let c=!b.g;if(b.l&&c)return 3;let e=a.i;var d=e[18];let f=e[1];var g=b.va;let h=b.N,k=b.ha||(g.search?null:h),l=b.h,m=La.includes(b.type),p=!b.I;var q=!m&&d.exec(g.href);if(q){var r=d.Xb,t=d.Yb;let z=d.Zb,x=d.$b;for(d=1;d<q.length;++d)if(q[d]){r=r[--d];if(null===r)break;var u=void 0;q=0;r.includes("G")&&(u=!0,q|="GET"==b.method);r.includes("P")&&(u=!0,q|="POST"==b.method);if(u&&!q)break;u=r.includes("V")|r.includes("A")|r.includes("C");r.includes("H")&&(b.V=!0);if((u?b.V:l?!r.includes("S"):
r.includes("X"))||p&&r.includes("D"))return 1;let y,S,H;if(q=x[d]){q=q.exec(g.href);if(!q)break;g=t[d];if(t=g.F)H=!0,S=q[t];if(t=g.T)H=!0,y=q[t]}y||=U(S)||r.includes("T")&&(H=!0,h)||z[d];if(u)return y&&(b.N=y),l||(b.h=!0),b.g=!0,6;if(c&&(y?f.test(y):!H))return b.M=16777216,4;break}}if(!c)return 6;if(k&&(m&&e[2].test(k)||l&&e[4].test(k)))return 1;if(a.N&&(b.I||e[-10])){if(l&&e[3].test(k))return 6;if((!l||a.v)&&k&&f.test(k))return b.M=8,4}return 6}
function uc(a,b){if(b.fa)return V(a,6,b),6;var c=b.statusCode;if(200!=c&&206!=c&&304!=c)return 1;var e=Z(b.o,"Content-Type"),d=Z(b.o,"Content-Disposition"),f=vc(e).toLowerCase();let g="attachment"==vc(d).toLowerCase();c=b.h;var h=b.C;if(b.ea=h&&!g&&"text/html"==f){if(b.j){var k=Ib(a,b);k&&(k.j=!0);V(a,5,b)}return 1}if(c?b.u:b.g)return 1;if(a.v&&h&&g)return 4;let l,m,p,q,r,t;var u;let z;let x,y=a.i,S=b.port,H=b.va;var ka=H.hostname;let wa=H.pathname,w=(d=wc(d,"filename")||wc(e,"name"))&&U(d);if(d){if(!w&&
!c)return 1;if(w&&(!c||5>=w.length)){var A=wc(e,"charset");x=!A||"utf-8"==A||"utf8"==A;A=!0}}A||(d=wa.split("/").pop(),(w=b.N||U(d))&&w.toLowerCase()==f.split("/").pop()&&(A=!0));if(!A){e=y[10].test(f);var M=za[f];M&&(M=M.split("|"),w&&M.includes(w)?A=!0:c&&Za(w)?A=!0:(c?e:w)||(A=!0,z=e,w=M[0]));!A&&w&&(g&&h?A=!0:e?A=z=!0:M||Ya(w)||(A=z=!0))}if(c){M=Lb(a,ka);h=a.$[M];e=wa+H.search;switch(M){case 0:break;case 1:if(h[111].test(e))l=A=!0,w=null;else if(h[112].test(e))m=!0;else if(h[115].test(e)&&"application/json"==
f)t=!0;else if(h[113].test(e)||h[114].test(e))p=!0;break;case 2:(ka=h[111].exec(e))&&(Xa(f)||"text/html"==f)?(f=ka[1]&&h[112].exec(S.B))&&ka[1]!=f[1]||(p=!0):h[114].test(e)?r=!0:g&&"image"==b.type&&"MP4"==w&&(u=!0);break;case 3:"M4S"==w&&(A=!0);ka==h[111]&&h[112].test(wa)&&Xa(f)&&(p=!0);break;case 4:h[111].test(e)&&Xa(f)&&(r=!0);break;case 5:h[111].test(e)&&"text/html"==f&&(r=!0);break;case 6:h[111].test(e)&&(p=!0);break;default:h[111].test(wa)&&(r=!0)}A&&("M3U8"==w||"F4M"==w||"MPD"==w?p=!0:"F4F"==
w&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(q=!0));"ASF"==w&&((f=Z(b.o,"Content-Length"))&&102400>=parseInt(f)&&(u=!0),"DCLK-AdSvr"==Z(b.o,"Server")&&(u=!0))}if(u)return 1;A&&(c&&y[3].test(w)?l=!0:c&&y[4].test(w)?b.g=!0:!b.g&&y[1].test(w)&&(k=!0));if(l){let Fb,Gb;if(b.V)l=!1;else if(u=y[11])u.test(H.hostname)?l=!1:(Fb=a.g[b.tabId])&&(Gb=Fb.B)&&u.test((new URL(Gb)).hostname)&&(l=!1)}if(r||t)r&&0>S.N||t&&0>S.u?p=!0:m=b.A=!0;if(p||q)"POST"!=b.method||b.i?(a=new XMLHttpRequest,
a.responseType=q?"blob":"text",b.m=a,m=!0):m=!1;if(!k&&!l&&!m)return 1;A&&(b.ha=w);x&&(b.P=d);b.j|=m;b.M=l||m?256:16|(c?4096:0)|(z?8388608:0);return k?4:l?2:5}
function V(a,b,c,e,d,f){var g=c.url,h=c.S||Q(g);let k=c.requestHeaders,l=1==(h&7);if(!d&&!k&&!e&&l)if(void 0===f){if(f=Z(k,"Cookie"),null==f)return R(g).then(y=>V(a,b,c,e,d,y||null))}else f=T(f);let m=d?d.id:c.id,p=c.port&&c.port.id,q=c.timeStamp,r=c.M,t=c.o,u=c.W,z=c.s,x=0;3==(z?z.length-z.replaceAll(".","").length:0)?r|=33554432:2<(z?z.length-z.replaceAll(":","").length:0)&&(r|=4194304);h&16&&(r|=2097152);"POST"==c.method&&(r|=512);d&&(x|=129);4>b&&e&&(x|=1);c.j&&c.m&&(x|=1);c.j&&5!=b&&(x|=32);
c.h&&(x|=16);c.H&&(x|=8192);c.C&&(x|=c.D?2048:4096);h=[m,p,C(q),c.statusCode,h&7,b,c.tabId,c.frameId];g={[6]:Qb(g,l&&a.P),[12]:c.statusLine,[17]:c.ba,[4]:c.ha,[100]:c.P,[127]:c.ka,[129]:c.ga,[2]:c.s,[122]:a.A,[8]:r,[11]:xc(k),[13]:xc(t),[18]:xc(u)};c.i&&(g[14]=oc(c.i,k));c.L&&(g[19]=oc(c.L,u));k||(g[50]=yc(a,c),g[51]=f,g[54]=navigator.userAgent);if(!c.ea||!c.D)if(f=a.g[c.tabId])g[7]=f.B;return!!P(a,13,1,x,h,g,e)}
function zc(a,b,c,e){var d=a.N?new XMLHttpRequest:null;let f=V(a,b,c,d);d&&((d=f&&parseInt(d.getResponseHeader("x-idm-status")))?f=3==d:f=V(a,b,c));if(f){if(!e){c.G=!0;return}return W(a,c,!0)}c.g=!0}
function W(a,b,c){let e=a.j;if(E(b)||(b=e[b])){var d=b.id,f=0<b.statusCode;if(c){if(b.C||b.H){let h=f||!b.requestHeaders;if((f=Ib(a,b))&&f.g&&b.D)browser.tabs.remove(b.tabId);else if(h&&!b.H)var g={redirectUrl:"javascript:void(0)"};else h&&((g=a.L)||(g=b.port,a=f&&!f.s,g=new URL(g&&g.B||b.url),g=Sa+(a?"back=1":`host=${g.hostname}`)),g={redirectUrl:g})}g||={cancel:!0};b.G=!0}(a=b.resolve)&&void 0!==c&&(b.resolve=b.reject=null,a(g||{}));if(c=b.reject)b.resolve=b.reject=null,c();if(b.Ka||b.m||b.A)return b.Fa=
!0,g;delete e[d];b.v&&delete e[b.v];return g}}n.Fb=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){let c=this.g[a.tabId];this.ja("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.B);W(this,a.requestId);(b=Ib(this,a))&&b.g&&"main_frame"==a.type&&browser.tabs.remove(a.tabId);return{redirectUrl:Sa+"register=1"}}};n.hb=function(a){if(!(0>a.tabId||a.initiator==Ua||this.xa||a.url.startsWith(Sa)&&a.type.endsWith("_frame")||a.url.startsWith(Ta)&&"main_frame"==a.type))return{cancel:!0}};
n.Za=function(a){var b=a.type,c=a.tabId,e=a.frameId;if(!(0>c&&a.initiator==Ua)){var d=a.url,f=a.method,g=Q(d);if(g&&("GET"==f||"POST"==f)&&d!=this.L){e&&"outermost_frame"==a.frameType&&(e=a.frameId=0);var h=a.id=a.requestId;h=this.j[h];var k=this.Da,l="POST"==f,m="image"==b,p="other"==b,q=!p&&0>c&&0>e,r=0<c&&b.endsWith("_frame");if((f=q?null:this.g[L(c,e)])||r||q||p||h){r&&Hb(this,a,null,!1);if(!k&&l&&a.requestBody){l=a.requestBody;var t=l.raw;if(t)for(let u=0;u<t.length&&(t[u].bytes||(t=null));u++);
if(!(t||l.formData||l.error))return}if((l=this.Aa)&&(t=f?f.id==l&&f:this.m[l])&&d==t.G){p=t.H;if(l=t.I)a.P=l,a.ha=U(l);f||=t;this.Aa=null}l=new URL(d);l.hash="";a.va=l;a.S=g;a.l=this.na;a.u=k;a.D=r&&"main_frame"==b;a.C=r;a.H=p;a.$=q;a.h=q||Ma.includes(b);a.g=m;a.j=this.Na.test(d);a.i=a.requestBody;a.port=f;a.I=g&8||this.sa[g];0>c&&(a.tabId=null);0>e&&(a.frameId=null);h&&(a.id=h.id,a.port=f=h.port,a.l=h.l,a.u=h.u,a.ba=h.ba||h.url,a.W=h.W||h.requestHeaders,a.L=h.L||h.i);if(a.h&&!m){b=this.fa;c=b.Qb;
e=c.indexOf(d);if(0<=e)c.splice(e,1);else for(;30<=c.length;)delete b[c.shift()];b[d]=f;c.push(d)}switch(a.action=sc(this,a)){case 1:a.g=!0;case 6:d=this.j;f=a.id;d[f]!==a&&(d[f]=a);break;case 4:return zc(this,1,a)}}}}};
n.Gb=function(a){var b=this.j[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.G){if(b.$&&!b.port&&(a=Z(c,"Referer")))for(var e of v(this.m))if(e.B==a){b.port=e;break}if(b.port&&b.port.m&&"xmlhttprequest"==b.type){var d,f;e=0;for(d of c)if("accept"==d.name.toLowerCase()&&(f=bb(d.value)))break;else e++;if(f){a=f[3];let h=f[4];var g=!0;f[1]||f[5]?d.value=f[1]+(f[5]&&f[2]||"")+f[5]:c.splice(e--,1);if("pxr"==a||"pfm"==a)b.v=h,this.j[h]=b}}if("POST"==b.method&&(!b.i||
b.i.error&&0<Z(c,"Content-Length")))return W(this,b);switch(b.action=tc(this,b)){case 1:b.g=!0;break;case 4:return zc(this,1,b);case 3:return zc(this,3,b)}if(g)return{requestHeaders:c}}}else if(0>a.tabId&&"xmlhttprequest"==a.type&&a.initiator==Ua){b=a.requestHeaders;c={};for(d=0;d<b.length;d++)f=b[d],e=f.name.toLowerCase(),e.startsWith("x-idm-")?c[e.substr(6)]=g=!0:"origin"==e&&f.value==Ua&&(c[e]=g=!0);if(g){for(g=0;g<b.length;g++)d=b[g],f=d.name.toLowerCase(),c[f]?b.splice(g--,1):f.startsWith("x-idm-")&&
(d.name=d.name.substr(6));return{requestHeaders:b}}}};
n.Ib=function(a){let b=this.j[a.requestId];if(b){var c=b.port,e=b.type,d=b.statusLine=a.statusLine,f=b.statusCode=a.statusCode||parseInt(d.split(" ",2).pop()),g=a.responseHeaders;if(b.G||204==f&&d.includes(" IDM "))return W(this,b,!0);b.s=a.ip;b.X=a.timeStamp;b.ga=C(a.timeStamp-b.timeStamp);b.o=g;b.fa=eb(f);if("image"==e&&(d=Z(g,"Content-Type"))&&d.toLowerCase().startsWith("image"))return W(this,b);"quic"==Z(g,"Client-Protocol")?b.S|=16:(d=Z(g,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=
Z(g,"Transfer-Encoding")&&(b.S|=16);if(c&&"xmlhttprequest"==e&&!b.v&&2==c.u){e=oa.map(Z.bind(J,g));e.unshift(b.url);e=e.join("|");d=5381;f=e.length;for(let h=0;h<f;h++)d=33*d+e.charCodeAt(h)>>>0;c=b.v=`${c.id}-${d}`;this.j[c]=b}switch(b.action=uc(this,b)){case 1:return W(this,b);case 4:return zc(this,2,b,a);case 3:return zc(this,3,b,a)}if(b.A)return g||=[],g.push({name:"x-idm-request-id",value:b.id.toString()}),{responseHeaders:g}}};
n.Jb=function(a){let b=this.j[a.requestId];if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){let c=Ib(this,a);c&&(c.B=a.url,c.ba=c.v)}b&&(b.s||(b.s=a.ip),2==b.action?V(this,4,b):5==b.action&&V(this,5,b),W(this,b))};n.Hb=function(a){W(this,a.requestId)};
async function tb(a){var b={url:Ea.homepage_url},c=F(browser.storage.local.get(null,G()));b=F(browser.cookies.getAll(b,G()));let e=F(browser.extension.isAllowedIncognitoAccess(G()));[c,b,e]=await Promise.all([c,b,e]);a.Ra=c.version;a.oa=c.silent;a.I=c.lastupt;a.Ma=e;a.I>Date.now()&&(a.I=null);c=c.client;let d;if(b)for(let f of b)switch(f.name){case "idmwebext_cid":d=parseInt(f.value)}gc(a,null,c,d);a.za()}
function gc(a,b,c,e){(b||=c||e)&&b!=a.M&&(a.M=b,c||browser.storage.local.set({client:b}),e||browser.cookies.set({url:Ea.homepage_url,name:"idmwebext_cid",value:String(b),expirationDate:2147483647}))}
function Mb(a){a.O&&(browser.tabs.remove(a.O),a.O=null);if(a.Sa){var b=!a.s,c=!a.Ma,e=a.P,d=a.ma,f=a.Ra,g=a.Pb;if(b){if(a.ka&&a.oa)return}else a.Sa=!1,g!=f&&g&&browser.storage.local.set({version:g}),a.oa&&(a.oa=!1,browser.storage.local.set({silent:!1}));null!=f&&(g==f||d&&f&&!e)||(g=Ta+"current="+escape(g),f&&(g+="&previous="+escape(f)),d&&(g+="&manager="+(d?[d>>24&255,d>>16&255,d>>8&255,d&255].join("."):"")),b&&(g+="&error=1"),c&&(g+="&incognito=1"),e&&(g+="&update=1"),browser.tabs.create({url:g+
"&msedge=1"},function(h){h&&(this.O=h.id)}.bind(a)))}}function hc(a,b,c){null==b&&(b=db(c[13]))&&(b=b[1]<<24|b[2]<<16|b[3]<<8);a.ma=b>>>0}function ic(a){a.P=103417600>a.ma;103424E3>a.ma?a.H=a.I?a.I+6E4*C(240*D()+480):Date.now():(a.H=a.I=null,browser.storage.local.remove("lastupt"))}
function Tb(a,b){var c=Date.now();if(c>a.H||b&&!a.P)browser.storage.local.set({lastupt:a.I=c}),0<a.H&&(a.H=c+6E4*C(240*D()+480)),c="idmdwnlmfv4://idmreg://"+D().toString(36).substr(2),b?a.ja(c):J.setTimeout(a.ja,C(5E3*D()+5E3),c)}function yc(a,b){a=a.D;b=L(b.tabId,b.frameId);var c;do b=(c=a[b])&&c.i,c=c&&c.B,"about:blank"==c&&(c=null);while(!c&&b);return c}function Sb(a){a=browser.i18n.getMessage(a);window.alert(a)}
n.K=function(a,b,c){if(null!=b){var e=da(arguments);this.Ia.push(e);b.addListener.apply(b,e.slice(2))}};n.Ja=function(){let a=arguments.length?da(arguments):null,b=this.Ia;for(let c=0;c<b.length;c++){if(a&&!a.includes(b[c][0]))continue;let e=b.splice(c--,1).pop(),d=e.splice(0,2).pop();d.removeListener.apply(d,e)}};function lc(a){return browser.i18n.getMessage(a)||a}
function Qb(a,b){let c=a.lastIndexOf("#");c>a.indexOf("?")&&"!"!=a[c+1]&&(a=a.substr(0,c));!b||a.startsWith("idmdwnlmfv")||$a(a)||(a=`${"idmdwnlmfv"}4://${a}`);return a}function Q(a,b){a=a.split(":",1).shift().toLowerCase();a=va[a]||0;return b?a&7:a}function U(a){return(a=cb(a))?a[1].toUpperCase():""}function R(a,b){a={url:a};b&&(a.session=!1);return F(browser.cookies.getAll(a,G())).catch(()=>null)}
function T(a){if(!E(a))return a;let b=[];for(let c of a)b.length&&b.push("; "),b.push(c.name,"=",c.value);return b.join("")}function xc(a){if(!a||!a.length)return null;let b=[];for(let c of a)b.push(c.name,": "),null!=c.value?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(let c of a)if(c.name.toLowerCase()==b){if(null!=c.value)return c.value;if(c.binaryValue)return ha(c.binaryValue)}return null}
function wc(a,b){if(!a)return null;let c,e;a=a.split(";");for(b=b.toLowerCase();a.length;){var d=a.shift();let g=d.indexOf("=");if(0<g){var f=d.slice(0,g).trim().toLowerCase();let h=f.endsWith("*");if(h)f=f.slice(0,-1).trimRight();else if(e)continue;if(f==b){f=d.substr(g+1).trim();d=f.length-1;if('"'==f[0]?'"'==f[d]:"'"==f[0]&&"'"==f[d])f=f.slice(1,d);if(h&&f.includes("'")){if(f=f.split("'",3),h=f.shift().toLowerCase(),f=f.pop(),((d="utf-8"==h||"utf8"==h)||!e)&&(c=Ac(f))&&(e=h,d))break}else c=Ac(f)}}else 0>
g&&null==c&&d.trim().toLowerCase()==b&&(c="")}return c}function vc(a){const b=/[;,]/;return(a&&=a.split(b,1).shift().trim())&&!a.includes("=")&&Ac(a)||""}function Ac(a){try{return a&&decodeURIComponent(a)}catch(b){return unescape(a)}}
function oc(a,b){let c;var e;let d=[];if(c=a.raw)for(e of c){var f=e.bytes;if(f)d.push(f);else return null}else if(e=a.formData)if(b=ca(b)?Z(b,"Content-Type"):b,(a=vc(b).toLowerCase())&&"application/x-www-form-urlencoded"!=a)if("multipart/form-data"==a){var g=wc(b,"boundary");g||="----WebKitFormBoundary"+D().toString(36).substr(2);for(f in e)for(let h of e[f])d.push("--",g,'\r\nContent-Disposition: form-data; name="',f,'"\r\n\r\n',h??"","\r\n");d.push("--",g,"--\r\n")}else return null;else for(g in e){f=
encodeURIComponent(g).replaceAll("%20","+");for(let h of e[g])h=h instanceof ArrayBuffer?escape(ha(new Uint8Array(h))):null==h?"":encodeURIComponent(h),d.length&&d.push("&"),d.push(f,"=",h&&h.replaceAll("%20","+"))}else return null;return d.length?d:null}function kb(a){let b=a.length,c=b,e=0;for(;e<c;){let d=a.charCodeAt(e++);128<=d&&(2048<=d?(b+=2,d-55296&64512||e++):b++)}return b}
function Bc(){let a="llbjbkhnmlidjebalopleeepgdfgcpec"==Da&&"ngpampappnmepgilojfohadhhmbhlaek";browser.management.get(a||"llbjbkhnmlidjebalopleeepgdfgcpec",function(b){browser.runtime.lastError;b&&b.enabled&&browser.management.setEnabled(a||Da,!1)})}function Cc(a,b,c){c?4==c.readyState&&(hb[a]=btoa(c.responseText)):(c=new XMLHttpRequest,c.responseType="text",c.onreadystatechange=Cc.bind(null,a,b,c),c.open("GET",browser.runtime.getURL(b)),c.send())}
function Y(a,b,c,e){if(b=b[c]||void 0){b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\.");b=1==e?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):3==e?b.replace(/(?<![*?])\*(?!\*)/g,"[^/]*").replace(/\?\*/g,"\\?.*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?");2==e&&(b=b.replace(/(^|\|)([^|]+?)~/g,"$1(?:$2\\.)?").replace(/(^|\|)~/g,"$1(?:.*?\\.)?"));b="^(?:"+b+")$";try{b=RegExp(b,1==e?"":"i")}catch(d){b=null}}a[c]=b||Ja}
function jc(a,b,c,e,d){b=b[c];let f=[],g=[],h=[],k=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)|\*+(?=\*)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(e){for(var l=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");l.length;){var m=l.shift();f.push(ab(m)?m:null);g.push(l.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(d){let p=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");l=/<([A-Z]):(.*?)>/g;m={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"};for(let q,r=0;p.length;++r)if(q=p.shift()){let t={},u=["^"],z="";for(let x,y=1;x=l.exec(q);++y)t[x[1]]=y++,z=RegExp.rightContext,u.push(RegExp.leftContext,"(",x[2].replace(/\*/g,m[x[1]]||".%%?"),")");u.push(z,"$");h[r]=t;k[r]=RegExp(u.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(l,"(?:$2)")}b=b.replace(/\*/g,".*?").replace(/%%/g,"*");b=e||d?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(p){b=
null}a[c]=b||=RegExp("(?!)");e&&(b.Xb=f,b.Zb=g);d&&(b.Yb=h,b.$b=k)}function fc(a){return browser.runtime.lastError?null:F(browser.permissions.request({permissions:[a]},G()))}function O(a){browser.runtime.lastError;a;!0}
const kc=[null,[!0,-8,"menu_download_link","link,image,video",N.prototype.Ba],[!0,-8,"menu_download_link","page,frame,editable",N.prototype.Ba,Qa],[!0,-8,"menu_download_selected","selection",N.prototype.La],[!0,-9,"menu_download_all","page,frame,editable",N.prototype.La],[!0,-8,"menu_download_item","link",N.prototype.Ba,["chrome://downloads/*"]]],yb=lc("tooltip_title"),Ab=lc("tooltip_disabled"),Bb=lc("tooltip_error"),zb="\n"+lc("tooltip_text");
(async function(){var a=F(browser.runtime.getPlatformInfo(G())),b;navigator.userAgentData&&(b=navigator.userAgentData.getHighEntropyValues(["fullVersionList","uaFullVersion"]));var c=F(browser.management.get("clhiejnehegdfknplplojohghjaklbae",G())).catch(()=>null);[a,b,f,c]=await Promise.all([a,b,f,c]);if(a&&"win"!=a.os)return xb(!1);Bc();a=navigator.userAgent;var e=a.match(/\s(?!(?:Chrome|Firefox|Gecko|Safari)\/)([A-Z]\w+)(?:\/(\d+(?:\.\d+){0,3}))?\b(?!.*\)\s+\S)/),d=a.match(/\s(Chrome|Firefox)\/(\d+(?:\.\d+){0,3})\b/);
a=d?d[1]:"UNKNOWN";var f=e?e[1]:a;d=d&&d[2]||"0.0";e=e&&e[2]||d;navigator.brave&&(f="Brave");c&&(f="Epic",Ca=!0);if(E(b)){if(c=b.uaFullVersion)e=c;if(b=b.fullVersionList)for(let g of b)if(c=g.version)switch(g.brand){case "Chromium":a="Chrome";parseInt(c)==parseInt(d)?d=c:(f="UNKNOWN",e=c);break;case f:e=c}}c=d.split(/\D+/);Aa=`${a}/${d}`;Ba=`${f}/${e}`;new N;Cc(1,"debug.js");Cc(2,"document.js")})();
